// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtsNQ2GeIp9pTzEjtdYIFZ7I8cw83lQb0',
    appId: '1:1039607356302:web:29c4397baefb78d9eda2df',
    messagingSenderId: '1039607356302',
    projectId: 'login-tws',
    authDomain: 'login-tws.firebaseapp.com',
    storageBucket: 'login-tws.firebasestorage.app',
    measurementId: 'G-XPYMTR3Y4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0X9ubOmhtzUWMIpBT4hyxsw2_0mSwH4w',
    appId: '1:1039607356302:android:9be144373ac9bc4feda2df',
    messagingSenderId: '1039607356302',
    projectId: 'login-tws',
    storageBucket: 'login-tws.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT_ipcAYipKpGDROcc-eShnjhW95HOwwc',
    appId: '1:1039607356302:ios:5cd3d07ddc0ce427eda2df',
    messagingSenderId: '1039607356302',
    projectId: 'login-tws',
    storageBucket: 'login-tws.firebasestorage.app',
    iosBundleId: 'com.example.flutter01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT_ipcAYipKpGDROcc-eShnjhW95HOwwc',
    appId: '1:1039607356302:ios:5cd3d07ddc0ce427eda2df',
    messagingSenderId: '1039607356302',
    projectId: 'login-tws',
    storageBucket: 'login-tws.firebasestorage.app',
    iosBundleId: 'com.example.flutter01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtsNQ2GeIp9pTzEjtdYIFZ7I8cw83lQb0',
    appId: '1:1039607356302:web:16a68296238327b4eda2df',
    messagingSenderId: '1039607356302',
    projectId: 'login-tws',
    authDomain: 'login-tws.firebaseapp.com',
    storageBucket: 'login-tws.firebasestorage.app',
    measurementId: 'G-0ZQTDXK15M',
  );
}
